name: activity-dekho-next-app-staging

on:
  push:
    branches:
      - staging

env:
  PROJECT_ID: ${{ secrets.CLOUD_RUN_PROJECT_NAME}}
  REGION: asia-south1
  REPO_NAME: activity-dekho-staging
  FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY}}
  FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID}}
  FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID}}
  
jobs:
  build-and-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # authenticate with google cloud
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }}"
      
      # setup gcloud CLI/SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      # giving docker permission ot push
      - name: Authorize Docker push
        run: gcloud auth configure-docker

      # build docker image
      - name: Build and tag the docker image
        run: |-
          docker build . --tag gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA          

      # pushing image to google container registry
      - name: Push the image to the Google Container Registry (GCR)
        run: |-
          docker push gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA

      - name: Deploy
        run: |-
          gcloud run deploy $REPO_NAME \
          --region $REGION \
          --image gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA \
          --platform "managed" \
          --quiet \
          --set-env-vars "NEXT_PUBLIC_FIREBASE_API_KEY=$FIREBASE_API_KEY" \
          --set-env-vars "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=aicte-diary.firebaseapp.com" \
          --set-env-vars "NEXT_PUBLIC_FIREBASE_PROJECT_ID=aicte-diary" \
          --set-env-vars "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=aicte-diary.appspot.com" \
          --set-env-vars "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID" \
          --set-env-vars "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_APP_ID" \
          